- name: play level variable
  hosts: local host
  vars:
    URL: play.example.com
  tasks:
    - name: print play level variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: play level variable from file
  hosts: local host
  vars_files:
    - var.yml
  tasks:
    - name: print play level variable from file
      ansible.builtin.debug:
        msg: URL = {{ URL }}




