- name: play level variable
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play level variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: play level variable from file
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: print play level variable from file
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: task level variable
  hosts: localhost
  tasks:
    - name: task level variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: variables from inventory
  hosts: all
  tasks:
        - name: variable from inventory
          ansible.builtin.debug:
            msg: "URL = {{ URL }} hostname of server {{ ansible_hostname }}"

-  name: register a variable
   hosts: localhost
   tasks:
       - name: get uptime output
         ansible.builtin.shell: uptime
         register: out

- name: print out
  ansible.builtin.debug:
       msg: "{{ out  }}"

- name: declare a variable
  ansible.builtin.set_fact:
    status: "{{ out.rc }}"

- name: print status
  ansible.builtin.debug:
     msg: "{{ status }}"









